"""
02_reproduce_schema.py
──────────────────────
Reproduce JSON Schemas from the generated (and enriched) Pydantic models.

Reads from : models/   (generated by 01_reverse_engineer.py, then enriched by the team)
Writes to  : reproduced/<schema_name>.schema.json

These reproduced schemas are what you send to the firewall team for signing.
Run 03_compare_schemas.py afterwards to produce the diff report.
"""

import enum
import importlib
import inspect
import json
import sys
from pathlib import Path
from pydantic import BaseModel, TypeAdapter

# ── Paths ─────────────────────────────────────────────────────────────────────
ROOT       = Path(__file__).parent
MODELS_OUT = ROOT / "models"
REPRODUCED = ROOT / "reproduced"

sys.path.insert(0, str(ROOT))

# ── Export targets ─────────────────────────────────────────────────────────────
# (output_filename, module_stem, class_name | None)
#   class_name=None  → combined $defs schema (all models in module)
#   class_name=str   → single top-level document model
EXPORT_TARGETS = [
    (
        "envelope.schema.json",
        "envelope_schema",
        "WmsEnvelope",           # top-level document model
    ),
    (
        "ZWMS_INBOUND_DELIVERY_CREATE.schema.json",
        "ZWMS_INBOUND_DELIVERY_CREATE_schema",
        "WmsinterfaceZwmsInboundDeliveryCreate",
    ),
    (
        "business-types.schema.json",
        "business_types_schema",
        None,                    # no single root — export all as $defs
    ),
]


def load_module(module_stem: str):
    try:
        return importlib.import_module(f"models.{module_stem}")
    except ModuleNotFoundError:
        print(f"  ✗ models.{module_stem} not found. Run 01_reverse_engineer.py first.")
        sys.exit(1)


def module_classes(module) -> dict[str, type]:
    """
    Return all exportable classes from the module:
    - BaseModel subclasses (Pydantic models)
    - Enum subclasses (StrEnum, IntEnum, etc.)
    Both are included so that enum $defs appear at the top level of the
    combined schema, matching the bootstrap structure.
    """
    result = {}
    for name, obj in inspect.getmembers(module, inspect.isclass):
        if obj.__module__ != module.__name__:
            continue
        if obj is BaseModel:
            continue
        if issubclass(obj, BaseModel) or issubclass(obj, enum.Enum):
            result[name] = obj
    return result


def _class_schema(cls: type) -> dict:
    """Get JSON schema for a BaseModel or Enum class."""
    if issubclass(cls, BaseModel):
        return cls.model_json_schema()
    return TypeAdapter(cls).json_schema()


def schema_for_class(cls: type[BaseModel]) -> dict:
    schema = cls.model_json_schema()
    schema["$schema"] = "https://json-schema.org/draft/2020-12/schema"
    schema.setdefault("title", cls.__name__)
    return schema


def combined_defs_schema(module, module_stem: str) -> dict:
    models = module_classes(module)
    defs   = {}
    for name, cls in sorted(models.items()):
        s = _class_schema(cls)
        s.pop("title", None)
        defs[name] = s
    return {
        "$schema":     "https://json-schema.org/draft/2020-12/schema",
        "title":       module_stem,
        "description": f"Combined schema — {len(defs)} models from {module_stem}.",
        "$defs":       defs,
    }


def reproduce(out_filename: str, module_stem: str, class_name: str | None) -> dict:
    module = load_module(module_stem)

    if class_name is None:
        schema = combined_defs_schema(module, module_stem)
        print(f"  Mode: combined $defs  ({len(schema['$defs'])} types)")
    else:
        cls = getattr(module, class_name, None)
        if cls is None:
            available = list(module_classes(module).keys())
            print(f"  ✗ Class '{class_name}' not found in models.{module_stem}")
            print(f"    Available: {available}")
            sys.exit(1)
        schema = schema_for_class(cls)
        print(f"  Mode: top-level class '{class_name}'")
        print(f"    properties : {len(schema.get('properties', {}))}")
        print(f"    $defs      : {len(schema.get('$defs', {}))}")

    return schema


def main():
    sep = "=" * 62
    print(sep)
    print("  WMS Schema Reproducer")
    print(sep)

    REPRODUCED.mkdir(exist_ok=True)

    for out_filename, module_stem, class_name in EXPORT_TARGETS:
        print(f"\n  ── {out_filename}")
        schema = reproduce(out_filename, module_stem, class_name)

        out_path = REPRODUCED / out_filename
        out_path.write_text(
            json.dumps(schema, ensure_ascii=False, indent=2),
            encoding="utf-8",
        )
        print(f"  ✓ reproduced/{out_filename}")

    print(f"\n{sep}")
    print("  Done. Run 03_compare_schemas.py to diff against bootstrap.")
    print(sep)


if __name__ == "__main__":
    main()
