"""
03_compare_schemas.py
─────────────────────
Compare bootstrap JSON Schemas against reproduced Pydantic-derived schemas.

Reads from : bootstrap/   (original signed schemas)
             reproduced/  (generated by 02_reproduce_schema.py)

Output     : console report + reproduced/COMPARISON_REPORT.txt

Differences fall into two categories:
  [EXPECTED]   Pydantic enrichment — validators, descriptions, Field() constraints
               added by the dev team. Document these for the firewall team.
  [REVIEW]     Structural changes — missing fields, type changes, required changes.
               These need explicit sign-off before firewall team re-signs.
"""

import copy
import json
from pathlib import Path
from typing import Any

# ── Paths ────────────────────────────────────────────────────────────────────
ROOT       = Path(__file__).parent
BOOTSTRAP  = ROOT / "bootstrap"
REPRODUCED = ROOT / "reproduced"

# ── Schema pairs to compare ───────────────────────────────────────────────────
COMPARE_PAIRS = [
    (
        BOOTSTRAP  / "wms_envelope.schema.json",
        REPRODUCED / "envelope.schema.json",
    ),
    (
        BOOTSTRAP  / "wms_business_types.schema.json",
        REPRODUCED / "business-types.schema.json",
    ),
    (
        BOOTSTRAP  / "ZWMS_INBOUND_DELIVERY_CREATE.schema.json",
        REPRODUCED / "ZWMS_INBOUND_DELIVERY_CREATE.schema.json",
    ),
]

# Keys that are expected to differ (Pydantic adds these)
PYDANTIC_ENRICHMENT_KEYS = {
    "title", "examples", "$anchor", "$comment", "$schema", "$id",
    "description",   # enriched descriptions are fine
}

# Keys whose changes are structural and need REVIEW
STRUCTURAL_KEYS = {
    "type", "pattern", "minLength", "maxLength", "minimum", "maximum",
    "enum", "const", "required", "additionalProperties",
    "minItems", "maxItems", "uniqueItems", "properties",
    "anyOf", "oneOf", "allOf", "items",
}


class Diff:
    def __init__(self):
        self.expected: list[str] = []   # enrichments — OK, just document
        self.review:   list[str] = []   # structural — needs sign-off
        self.missing:  list[str] = []   # in bootstrap, gone from reproduced
        self.added:    list[str] = []   # new in reproduced, not in bootstrap

    def summary(self) -> str:
        lines = []
        if self.missing:
            lines.append(f"\n  ── MISSING FROM REPRODUCED ({len(self.missing)}) ── [REVIEW REQUIRED]")
            for m in self.missing:
                lines.append(f"    ✗ {m}")
        if self.added:
            lines.append(f"\n  ── ADDED IN REPRODUCED ({len(self.added)}) ── [EXPECTED — Pydantic enrichment]")
            for a in self.added:
                lines.append(f"    + {a}")
        if self.review:
            lines.append(f"\n  ── STRUCTURAL CHANGES ({len(self.review)}) ── [REVIEW REQUIRED]")
            for r in self.review:
                lines.append(f"    Δ {r}")
        if self.expected:
            lines.append(f"\n  ── EXPECTED ENRICHMENTS ({len(self.expected)}) ── [Document for firewall team]")
            for e in self.expected:
                lines.append(f"    ~ {e}")
        if not any([self.missing, self.added, self.review, self.expected]):
            lines.append("\n  ✓ Schemas are structurally identical.")
        return "\n".join(lines)

    @property
    def has_issues(self) -> bool:
        return bool(self.missing or self.review)


def _normalize_refs_in(obj: Any) -> Any:
    """Recursively reduce all $ref values to their local #/$defs/... fragment."""
    if isinstance(obj, dict):
        return {
            k: ("#/$defs/" + v.split("#/$defs/")[-1] if k == "$ref" and isinstance(v, str) and "#/$defs/" in v else _normalize_refs_in(v))
            for k, v in obj.items()
        }
    if isinstance(obj, list):
        return [_normalize_refs_in(i) for i in obj]
    return obj


def _ref_rewrite_classify(orig: str, new: str) -> str:
    """
    Classify a $ref value change.
    Returns 'expected', 'review', or 'rename' (structural — def name changed).
    """
    is_external = isinstance(orig, str) and orig.startswith("http") and "#/$defs/" in orig
    is_local    = isinstance(new,  str) and new.startswith("#/$defs/")
    if not (is_external and is_local):
        return "review"
    orig_name = orig.split("#/$defs/")[-1]
    new_name  = new.split("#/$defs/")[-1]
    if orig_name == new_name or orig_name.replace("_", "") == new_name:
        return "expected"
    return "rename"


def _is_optional_expansion(orig: dict, new: dict) -> bool:
    """
    Detect Pydantic's Optional[X] rendering for any field type:
      orig: {<constraints>}
      new:  {anyOf: [{<constraints>}, {type: null}], default: null, [title: ...]}

    Handles both:
      - {"$ref": "url"}         → {"anyOf": [{"$ref": "#/$defs/X"}, {"type": "null"}]}
      - {"type": "string", ...} → {"anyOf": [{"type": "string", ...}, {"type": "null"}]}

    Constraints supplied via `json_schema_extra` (e.g. uniqueItems) are emitted
    by Pydantic as SIBLINGS of anyOf rather than inside the non-null branch:

      {"anyOf": [{type: array, items: …, maxItems: 999}, {type: null}],
       "uniqueItems": true}

    They are merged into the non-null branch before comparing, so the field
    still matches its bootstrap definition. Merging (rather than ignoring the
    key) keeps the check honest: a constraint that is genuinely absent from
    both places still fails to match and is reported.
    """
    if "anyOf" not in new:
        return False
    any_of = new.get("anyOf", [])
    if len(any_of) != 2:
        return False
    if {"type": "null"} not in any_of:
        return False

    non_null = next(item for item in any_of if item != {"type": "null"})

    # For $ref fields: only check that a $ref is present (URL may differ from local)
    if set(orig.keys()) == {"$ref"}:
        return "$ref" in non_null

    # For inline types: non-null branch should match orig (ignoring title + enrichment keys).
    # Normalize $ref URLs to local fragments before comparing (bootstrap may use external URLs).
    ignore = PYDANTIC_ENRICHMENT_KEYS | {"default"}

    # Fold anyOf's siblings in with the non-null branch. The branch wins on
    # conflict — it is the more specific statement of the constraint.
    siblings = {k: v for k, v in new.items() if k not in ignore and k != "anyOf"}
    merged   = {**siblings, **non_null}

    orig_norm   = _normalize_refs_in(orig)
    merged_norm = _normalize_refs_in(merged)
    orig_stripped   = {k: v for k, v in orig_norm.items()   if k not in ignore}
    merged_stripped = {k: v for k, v in merged_norm.items() if k not in ignore}
    return orig_stripped == merged_stripped


def compare_values(path: str, orig: Any, new: Any, diff: Diff):
    """Recursively compare two JSON values, recording differences."""
    if orig == new:
        return

    key = path.split(".")[-1].split("[")[-1].rstrip("]")

    if isinstance(orig, dict) and isinstance(new, dict):
        compare_dicts(path, orig, new, diff)
        return

    if isinstance(orig, list) and isinstance(new, list):
        compare_lists(path, orig, new, diff)
        return

    # $ref changes: classify as expected rewrite, structural rename, or review
    if key == "$ref":
        kind = _ref_rewrite_classify(orig, new)
        if kind == "expected":
            diff.expected.append(f"{path}: external → local ref")
        elif kind == "rename":
            diff.review.append(f"{path}: ref rewrite with def name change: '{orig}' → '{new}'")
        else:
            diff.review.append(f"{path}: '{orig}' → '{new}'")
        return

    # Scalar difference
    if key in PYDANTIC_ENRICHMENT_KEYS:
        diff.expected.append(f"{path}: '{orig}' → '{new}'")
    elif key in STRUCTURAL_KEYS:
        diff.review.append(f"{path}: '{orig}' → '{new}'")
    else:
        # Unknown key — flag for review
        diff.review.append(f"{path}: '{orig}' → '{new}'  [unknown key — verify]")


def compare_dicts(path: str, orig: dict, new: dict, diff: Diff):
    """Compare two dicts, noting missing/added/changed keys."""
    # Detect: {"$ref": "url"} → {"anyOf": [{$ref: local}, {type: null}], "default": null}
    # This is Pydantic's Optional[X] rendering — expected enrichment, not a missing field.
    if _is_optional_expansion(orig, new):
        diff.expected.append(f"{path}: $ref → Optional (Pydantic anyOf+null pattern)")
        return

    orig_keys = set(orig.keys())
    new_keys  = set(new.keys())

    for k in sorted(orig_keys - new_keys):
        child_path = f"{path}.{k}"
        if k in PYDANTIC_ENRICHMENT_KEYS:
            diff.expected.append(f"{child_path}: removed (was: '{orig[k]}')")
        elif k == "allOf":
            # allOf is always flattened into top-level properties by preprocessing
            # (flatten_allof in 01_reverse_engineer.py) — its absence is expected.
            diff.expected.append(f"{child_path}: flattened by preprocessing (expected)")
        else:
            diff.missing.append(f"{child_path}  (was: {json.dumps(orig[k])[:80]})")

    for k in sorted(new_keys - orig_keys):
        child_path = f"{path}.{k}"
        if k in PYDANTIC_ENRICHMENT_KEYS:
            diff.expected.append(f"{child_path}: added → '{new[k]}'")
        else:
            diff.added.append(f"{child_path}  (value: {json.dumps(new[k])[:80]})")

    for k in sorted(orig_keys & new_keys):
        compare_values(f"{path}.{k}", orig[k], new[k], diff)


def compare_lists(path: str, orig: list, new: list, diff: Diff):
    """Compare lists — order-insensitive for simple scalars, positional for objects."""
    if all(isinstance(i, str) for i in orig + new):
        orig_set = set(orig)
        new_set  = set(new)
        for item in sorted(orig_set - new_set):
            diff.review.append(f"{path}: item removed: '{item}'")
        for item in sorted(new_set - orig_set):
            diff.added.append(f"{path}: item added: '{item}'")
        return

    # Object lists — compare positionally
    for i, (o, n) in enumerate(zip(orig, new)):
        compare_values(f"{path}[{i}]", o, n, diff)
    if len(orig) > len(new):
        for i in range(len(new), len(orig)):
            diff.missing.append(f"{path}[{i}]: item removed")
    if len(new) > len(orig):
        for i in range(len(orig), len(new)):
            diff.added.append(f"{path}[{i}]: item added")


def _reconcile_def_names(orig: dict, new: dict) -> tuple[dict, list[str]]:
    """
    Pre-processing step: rename $defs keys in 'new' to match 'orig' where
    the only difference is underscore stripping (datamodel-codegen normalization).
    e.g. orig has ASN_ALLOW_PICK, new has ASNALLOWPICK → rename to ASN_ALLOW_PICK.
    Returns (modified_new, list_of_rename_messages).
    """
    orig_defs = set(orig.get("$defs", {}).keys())
    new_defs  = set(new.get("$defs", {}).keys())

    # Map from normalized (no underscores) → original bootstrap name
    norm_to_orig: dict[str, str] = {
        k.replace("_", ""): k
        for k in orig_defs
        if "_" in k
    }

    renames: dict[str, str] = {}  # new_name → orig_name
    for new_name in new_defs:
        if new_name not in orig_defs and new_name in norm_to_orig:
            renames[new_name] = norm_to_orig[new_name]

    if not renames:
        return new, []

    new = copy.deepcopy(new)

    # Rename the $defs keys
    for old_name, canonical in renames.items():
        new["$defs"][canonical] = new["$defs"].pop(old_name)

    # Update every $ref that pointed to the old name
    schema_str = json.dumps(new)
    for old_name, canonical in renames.items():
        schema_str = schema_str.replace(
            f'"#/$defs/{old_name}"', f'"#/$defs/{canonical}"'
        )
    new = json.loads(schema_str)

    msgs = [
        f"$root.$defs.{old} → {canonical}  (codegen underscore normalisation — expected)"
        for old, canonical in sorted(renames.items())
    ]
    return new, msgs


def compare_schemas(bootstrap_path: Path, reproduced_path: Path) -> tuple[Diff, str]:
    """Load and compare a bootstrap/reproduced schema pair."""
    if not reproduced_path.exists():
        diff = Diff()
        diff.missing.append(f"reproduced file does not exist: {reproduced_path.name}")
        return diff, f"MISSING: {reproduced_path.name}"

    orig = json.loads(bootstrap_path.read_text(encoding="utf-8"))
    new  = json.loads(reproduced_path.read_text(encoding="utf-8"))

    new, rename_msgs = _reconcile_def_names(orig, new)

    diff = Diff()
    for msg in rename_msgs:
        diff.expected.append(msg)
    compare_dicts("$root", orig, new, diff)
    return diff, ""


def stats(diff: Diff) -> str:
    return (
        f"Missing: {len(diff.missing)}  |  "
        f"Structural Δ: {len(diff.review)}  |  "
        f"Added: {len(diff.added)}  |  "
        f"Enrichments: {len(diff.expected)}"
    )


def main():
    separator = "=" * 64
    report_lines = []

    def out(line: str = ""):
        print(line)
        report_lines.append(line)

    out(separator)
    out("  WMS Schema Comparison Report")
    out("  Bootstrap (signed) ↔ Reproduced (Pydantic-derived)")
    out(separator)

    all_clean = True

    for bootstrap_path, reproduced_path in COMPARE_PAIRS:
        out(f"\n{'─' * 64}")
        out(f"  Comparing: {bootstrap_path.name}")
        out(f"  {'─' * 60}")

        if not bootstrap_path.exists():
            out(f"  ✗ Bootstrap file not found: {bootstrap_path}")
            continue

        diff, err = compare_schemas(bootstrap_path, reproduced_path)

        if err:
            out(f"  ✗ {err}")
            all_clean = False
            continue

        out(f"  {stats(diff)}")
        out(diff.summary())

        if diff.has_issues:
            all_clean = False

    out(f"\n{'=' * 64}")
    if all_clean:
        out("  ✓ All schemas pass structural comparison.")
        out("    Enrichments documented above — include in firewall team review package.")
    else:
        out("  ✗ Structural differences found — review required before signing.")
    out(separator)

    # Write report file
    REPRODUCED.mkdir(exist_ok=True)
    report_path = REPRODUCED / "COMPARISON_REPORT.txt"
    report_path.write_text("\n".join(report_lines) + "\n", encoding="utf-8")
    print(f"\n  Report saved → reproduced/COMPARISON_REPORT.txt")


if __name__ == "__main__":
    main()
