# generated by datamodel-codegen:
#   filename:  business-types.schema.json
#   timestamp: 2026-04-09T22:23:29+00:00

from __future__ import annotations

try:
    from enum import StrEnum  # Python 3.11+
except ImportError:  # Python 3.10 and earlier
    from enum import Enum

    class StrEnum(str, Enum):
        """Backport of enum.StrEnum (added in 3.11) for the Python 3.10 target."""

        __str__ = str.__str__

from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field, RootModel


class WmsBusinessTypes(RootModel[Any]):
    root: Annotated[Any, Field(title='WmsBusinessTypes')]
    """
    Shared WMS business-domain vocabulary. Owned by the WMS/recipient team — NOT the firewall. Declares reusable primitives and composites used across multiple payload schemas. Changing a type here (e.g. extending MaterialNumber length) is a business/master-data decision and never touches the firewall schema.
    """


class SapDocumentNumber(RootModel[str]):
    root: Annotated[
        str,
        Field(
            examples=['0703891136', '0000000001'],
            max_length=10,
            min_length=10,
            pattern='^[0-9]{10}$',
        ),
    ]
    """
    SAP 10-digit zero-padded document number (DOCUMENT_NUM_SAP).
    """


class SapItemNumber(RootModel[str]):
    root: Annotated[
        str,
        Field(
            examples=['00010', '00020', '00030'],
            max_length=5,
            min_length=5,
            pattern='^[0-9]{5}$',
        ),
    ]
    """
    SAP 5-digit zero-padded document line-item number (DOCUMENT_ITEM_SAP). Increments by 10: 00010, 00020, 00030.
    """


class StorageLocation(RootModel[str]):
    root: Annotated[
        str,
        Field(
            examples=['3000', 'PA30', '0001'],
            max_length=4,
            min_length=4,
            pattern='^[A-Z0-9]{4}$',
        ),
    ]
    """
    SAP 4-character storage location code. Uppercase alphanumeric.
    """


class CustomerNumber(RootModel[str]):
    root: Annotated[
        str,
        Field(
            examples=['0000004003', '0000000001'],
            max_length=10,
            min_length=10,
            pattern='^[0-9]{10}$',
        ),
    ]
    """
    SAP 10-digit zero-padded customer/business partner number.
    """


class MaterialNumber(RootModel[str]):
    root: Annotated[
        str,
        Field(
            examples=['319657933', '000000000319657933'],
            max_length=40,
            min_length=1,
            pattern='^[0-9A-Z\\-]{1,40}$',
        ),
    ]
    """
    SAP material number. Numeric in standard systems; may contain uppercase and hyphens in extended configurations.
    """


class WmsOrderType(StrEnum):
    """
    WMS order type code (WMS_ORD_TP). Determines which DOC_HEADER payload schema branch fires in Layer 2. 101=inbound transfer, 201=outbound transfer, 301=inventory adjustment, 401=vendor return, 501=cross-dock. Extend this enum when new order types are onboarded — requires only a business-types update, not a firewall change.
    """

    field_101 = '101'
    field_201 = '201'
    field_301 = '301'
    field_401 = '401'
    field_501 = '501'


class DocumentCategory(RootModel[str]):
    root: Annotated[
        str,
        Field(
            examples=['01', '02', '10'],
            max_length=2,
            min_length=2,
            pattern='^[0-9]{2}$',
        ),
    ]
    """
    2-digit zero-padded document category code.
    """


class SapDocumentType(RootModel[str]):
    root: Annotated[
        str,
        Field(
            examples=['Z21', 'WA', 'WE'],
            max_length=4,
            min_length=2,
            pattern='^[A-Z0-9]{2,4}$',
        ),
    ]
    """
    SAP document type code. Uppercase alphanumeric, 2–4 chars. Custom types begin with 'Z'.
    """


class TwoDigitCode(RootModel[str]):
    root: Annotated[
        str,
        Field(
            examples=['00', '01', '10', '99'],
            max_length=2,
            min_length=2,
            pattern='^[0-9]{2}$',
        ),
    ]
    """
    Generic 2-digit numeric code. Used for CUSTOMER_TYPE, DELIVERY_PRIORITY, SHIP_CON and similar SAP code fields.
    """


class SapQuantity(RootModel[str]):
    root: Annotated[
        str,
        Field(
            examples=['1.000', '10.500', '999.999'],
            max_length=20,
            min_length=5,
            pattern='^[0-9]+\\.[0-9]{3}$',
        ),
    ]
    """
    SAP quantity as a decimal string with exactly 3 decimal places, as transmitted in IDocs and WMS interfaces.
    """


class CoordinateDecimal(RootModel[str]):
    root: Annotated[
        str,
        Field(
            examples=['0.000000000000', '32.085300000000', '-118.243683000000'],
            max_length=22,
            min_length=14,
            pattern='^-?[0-9]+\\.[0-9]{12}$',
        ),
    ]
    """
    Geographic coordinate as a decimal string with exactly 12 decimal places. Zero value is '0.000000000000'.
    """


class SerialNumber(RootModel[str]):
    root: Annotated[
        str,
        Field(
            examples=['SN-20240101-00001', 'ABC123456789'],
            max_length=30,
            min_length=1,
            pattern='^[A-Z0-9\\-]{1,30}$',
        ),
    ]
    """
    Equipment/serial number. Uppercase alphanumeric with hyphens. Used in SERIAL_NUMBERS arrays for serial-number managed materials.
    """


class WeightDecimal(RootModel[str]):
    root: Annotated[
        str,
        Field(
            examples=['12.500', '1000.000'],
            max_length=20,
            min_length=5,
            pattern='^[0-9]+\\.[0-9]{3}$',
        ),
    ]
    """
    Weight value with exactly 3 decimal places (kg by default unless WEIGHT_UNIT is set).
    """


class LinearDimension(RootModel[str]):
    root: Annotated[
        str,
        Field(
            examples=['120.00', '80.00', '100.50'],
            max_length=10,
            min_length=4,
            pattern='^[0-9]+\\.[0-9]{2}$',
        ),
    ]
    """
    Linear dimension (length/width/height) with exactly 2 decimal places.
    """


class HuType(StrEnum):
    """
    Handling unit type. PAL=euro pallet, BOX=carton box, BAG=bulk bag, CTN=ISO container, PLT=flat pallet, TRL=trailer load.
    """

    PAL = 'PAL'
    BOX = 'BOX'
    BAG = 'BAG'
    CTN = 'CTN'
    PLT = 'PLT'
    TRL = 'TRL'


class DimensionUnit(StrEnum):
    """
    Unit of measure for linear dimensions used in HU DIMENSIONS objects.
    """

    MM = 'MM'
    CM = 'CM'
    M = 'M'
    IN = 'IN'


class WeightUnit(StrEnum):
    """
    Unit of measure for weight fields (GROSS_WEIGHT, TARE_WEIGHT).
    """

    KG = 'KG'
    G = 'G'
    LB = 'LB'
    T = 'T'


class QualityDecision(StrEnum):
    """
    Quality usage decision code attached to an inspection lot. A=Accept (unrestricted stock), R=Reject (returns to vendor or scrap), P=Partial accept (split stock), N=Not yet decided (inspection still open).
    """

    A = 'A'
    R = 'R'
    P = 'P'
    N = 'N'


class InspectionCharResult(StrEnum):
    """
    Result of evaluating a single quality inspection characteristic. NA=not applicable for this material, PENDING=awaiting lab result.
    """

    PASS = 'PASS'
    FAIL = 'FAIL'
    NA = 'NA'
    PENDING = 'PENDING'


class SapAdjustmentQuantity(RootModel[str]):
    root: Annotated[
        str,
        Field(
            examples=['-2.000', '5.000', '-100.000'],
            max_length=21,
            min_length=5,
            pattern='^-?[0-9]+\\.[0-9]{3}$',
        ),
    ]
    """
    Signed SAP quantity for inventory adjustments. Positive = stock increase, negative = stock decrease. Same 3-decimal-place format as SapQuantity but permits a leading minus sign.
    """


class AdjustmentReason(StrEnum):
    """
    Reason code for an inventory adjustment line (WMS_ORD_TP=301). Required on every adjustment item.
    """

    SHRINKAGE = 'SHRINKAGE'
    DAMAGE = 'DAMAGE'
    COUNT_CORRECTION = 'COUNT_CORRECTION'
    THEFT = 'THEFT'
    EXPIRY = 'EXPIRY'
    SYSTEM_ERROR = 'SYSTEM_ERROR'


class HuDimensions(BaseModel):
    """
    Physical outer dimensions of a handling unit. All values in the unit specified by UNIT field.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    LENGTH: LinearDimension
    WIDTH: LinearDimension
    HEIGHT: LinearDimension
    UNIT: DimensionUnit


class SERIALNUMBER(RootModel[str]):
    root: Annotated[str, Field(max_length=0)]


class HuItem(BaseModel):
    """
    A single material line packed inside a handling unit. Represents the physical packing detail — what material, which batch, how many, and optionally the serial number.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    MATERIAL: MaterialNumber
    BATCH: Annotated[str | None, Field(max_length=10)] = None
    QUANTITY: SapQuantity
    SERIAL_NUMBER: SERIALNUMBER | SerialNumber | None = None


class HandlingUnit(BaseModel):
    """
    A physical handling unit (pallet, box, container) assigned to a document item. Demonstrates three levels of nesting: HandlingUnit → DIMENSIONS (nested object) + ITEMS (array of HuItem dicts).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    HU_NUMBER: Annotated[str, Field(pattern='^[0-9]{18,20}$')]
    """
    SAP HU number. 18–20 digit SSCC-format barcode printed on the label.
    """
    HU_TYPE: HuType
    GROSS_WEIGHT: WeightDecimal | None = None
    TARE_WEIGHT: WeightDecimal | None = None
    WEIGHT_UNIT: WeightUnit | None = None
    DIMENSIONS: HuDimensions | None = None
    ITEMS: Annotated[list[HuItem], Field(max_length=200, min_length=1)]
    """
    Materials packed inside this HU. Each entry is an HuItem dict (MATERIAL, BATCH, QUANTITY, SERIAL_NUMBER).
    """


class SHELFLIFEEXPDATE(SERIALNUMBER):
    pass


class NUMERICVALUE(SERIALNUMBER):
    pass


class NUMERICVALUE1(RootModel[str]):
    root: Annotated[str, Field(pattern='^-?[0-9]+\\.[0-9]{1,6}$')]


class InspectionCharacteristic(BaseModel):
    """
    A single quality characteristic evaluated during goods receipt inspection. Attribute checks (visual, label) use RESULT only; quantitative checks (weight, temperature) also carry NUMERIC_VALUE and LOWER/UPPER limits.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    CHAR_NAME: Annotated[str, Field(max_length=30)]
    """
    SAP inspection characteristic name (e.g. LABEL_CHECK, NET_WEIGHT, TEMP_STORAGE).
    """
    RESULT: InspectionCharResult
    NUMERIC_VALUE: NUMERICVALUE | NUMERICVALUE1 | None = None
    UNIT: Annotated[str | None, Field(max_length=10)] = None
    """
    Unit of measure for NUMERIC_VALUE (e.g. KG, C, MM). Blank for attribute characteristics.
    """
    LOWER_LIMIT: Annotated[str | None, Field(max_length=20)] = None
    """
    Minimum acceptable value for quantitative characteristics.
    """
    UPPER_LIMIT: Annotated[str | None, Field(max_length=20)] = None
    """
    Maximum acceptable value for quantitative characteristics.
    """


class TRANSITDOCKINGPLANT(SERIALNUMBER):
    pass


class DESCRIPTIONHE(RootModel[str]):
    root: Annotated[str, Field(max_length=1)]
    """
    תיאור הפריט בעברית
    """


class DESCRIPTIONEN(RootModel[str]):
    root: str
    """
    תיאור הפריט באנגלית
    """


class MESHEK(RootModel[str]):
    root: str
    """
    משק פריטי
    """


class NSCGROUP(RootModel[str]):
    root: str
    """
    קבוצת חומר NSC
    """


class SERIALPROFILE(RootModel[str]):
    root: str
    """
    פרופיל מס"ד
    """


class BATCHINDICATOR(RootModel[str]):
    root: str
    """
    סמן סדרה
    """


class STATUS(RootModel[str]):
    root: Annotated[str, Field(max_length=1)]
    """
    סטאטוס פריט
    """


class STOCKINDICATOR(RootModel[str]):
    root: str
    """
    אינדיקציית פריט מנוהל מלאי כן/לא
    """


class UNITOFMEASURE(RootModel[str]):
    root: str
    """
    יחידת מידה של הפריט
    """


class STORAGEMETHOD(RootModel[str]):
    root: str
    """
    תנאי אחסנה (טור 21)
    """


class MINTEMPERATURE(RootModel[str]):
    root: str
    """
    טמפ' מינימלית לאופן אחסנת הפריט
    """


class MAXTEMPERATURE(RootModel[str]):
    root: str
    """
    טמפ' מיקסימלית לאופן אחסנת הפריט
    """


class HUMIDITY(RootModel[str]):
    root: str
    """
    אחוז לחות מקסימלי לאופן אחסנת הפריט
    """


class SUPPLYCENTER(RootModel[str]):
    root: str
    """
    משק על - טור 02  מערך
    """


class SUPPLYSECTION(RootModel[str]):
    root: str
    """
    מדור משביר טור 03 קוד מדור
    """


class PRODUCTMANAGER(RootModel[str]):
    root: str
    """
    מנהל פריט טור 15
    """


class MANAGERNAME(RootModel[str]):
    root: str
    """
    שם מנהל פריט
    """


class MANAGERTEL(RootModel[str]):
    root: str
    """
    טלפון מנהל פריט
    """


class GENERALSKU(RootModel[str]):
    root: str
    """
    אינדיקציית מק"ט כללי
    """


class VERSION(RootModel[str]):
    root: str
    """
    אינדיקציית פריט מנוהל גרסה
    """


class SHELFLIFEWMS(RootModel[str]):
    root: str
    """
    חיי מדף WMS
    """


class EXPIRTAIONDATEINDICATOR(RootModel[str]):
    root: str
    """
    אינדיקציית פריט ניהול פג תוקף WMS
    """


class MINSHELFLIFE(RootModel[str]):
    root: str
    """
    מינימום חיי מדף לקליטה
    """


class TAKINACHZAKA(RootModel[str]):
    root: str
    """
    חייב בנתונים אחזקתיים.
    """


class SIVUGBITCHONI(RootModel[str]):
    root: str
    """
    סיווג ביטחוני
    """


class ATTRACTIVEITEM(RootModel[str]):
    root: str
    """
    אינדיקציית פריט חמיד (פריט אטרקטיבי)
    """


class STOCKCOUNT(RootModel[str]):
    root: str
    """
    מס ימים לספירה מחזורית
    """


class MATERIALSUBCATEGORY(RootModel[str]):
    root: str
    """
    תת משפחה
    """


class ACCOMPANYINGITEM(RootModel[str]):
    root: str
    """
    אינדיקציית פריט עיקרי, מצביע האם לפריט יש נלווים
    """


class SPECIALTRACE(RootModel[str]):
    root: str
    """
    מעקב מיוחד טור 11
    """


class WMSMATERIALGROUP(RootModel[str]):
    root: str
    """
    קבוצת פריטים
    """


class MATERIALTYPE(RootModel[str]):
    root: str
    """
    סוג חומר מהקט"מ
    """


class BREAKABLE(RootModel[str]):
    root: str
    """
    אינדיקציית פריט שביר
    """


class TOTALSHELFLIFE(RootModel[str]):
    root: str
    """
    סך חיי מדף לפריט
    """


class MANAGEDPARTNUMBER(RootModel[str]):
    root: str
    """
    אינדקצית מנוהל מקט  יצרן
    """


class UNID(RootModel[str]):
    root: str
    """
    שדה המייצג את החומר המסוכן
    """


class UNSEQUENCE(RootModel[str]):
    root: str
    """
    שדה המייצג מספור פנימי לנתוני חומר מסוכן מכיוון שיכול לקרות מצב שבו מספר או"ם מופיע יותר ממופע אחד. ומספר או"ם אינו חובה.
    """


class MAINUN(RootModel[str]):
    root: str
    """
    שדה המצביע על האו"ם המוביל במק"ט מכיוון שיכול לקרות מצב שבו למק"ט יהיה יותר מאו"ם אחד ולכן יש לתת מענה לאו"ם הראשי במק"ט. סימון X עבור האו"ם המוביל. או"ם מוביל אחד למק"ט
    """


class UNHEDESC(RootModel[str]):
    root: str
    """
    שם העברי של החומר המסוכן
    """


class UNENDESC(RootModel[str]):
    root: str


class MAINGROUP(RootModel[str]):
    root: str
    """
    קבוצות הסיכון אליה משויך החומר
    """


class SECONDARYGROUP(RootModel[str]):
    root: str
    """
    קבוצת הסיכון המשנית אליה משויך החומר
    """


class EMERGENCYCODE(RootModel[str]):
    root: str
    """
    מסמן את אופן הטיפול בחומר בעת אירוע בטיחות בחומ"ס. לכל תו בקוד חרום יש משמעות
    """


class NFPARED(RootModel[str]):
    root: str
    """
    מידת הדליקות
    """


class NFPABLUE(RootModel[str]):
    root: str
    """
    סיכון הבריאותי
    """


class NFPAYELLOW(RootModel[str]):
    root: str
    """
    מידת הפעילות הכימית
    """


class NFPAWHITE(RootModel[str]):
    root: str
    """
    סיכונים מיוחדים
    """


class MATCHGROUP(RootModel[str]):
    root: str
    """
    איזה קבוצות חומרים קיים פוטנציאל לתגובה כימית ולכן אסור לאחסנם או להבילם יחדיו
    """


class MATTERSTATE(RootModel[str]):
    root: str
    """
    מצב צבירה של החומר המסוכן
    """


class PACKTYPE(RootModel[str]):
    root: str
    """
    אריזה של החומר כגון: חבית, ג'ריקן, מארז וכו'.
    """


class PACKQUAN(RootModel[str]):
    root: str
    """
    הכמות מהחומר המסוכן באריזה
    """


class UNUNITOFMEASURE(RootModel[str]):
    root: str
    """
    יחידת המידה של החומר המסוכן לדוגמא : ק"ג, ליטר וכו'.
    """


class CHEMCOMP(RootModel[str]):
    root: str
    """
    הרכב הכימי של התרכובות של החומר המסוכן
    """


class CHEMSEQUENCE(RootModel[str]):
    root: str
    """
    מספור פנימי לנתוני חומר מסוכן
    """


class CONCENTRATION(RootModel[float]):
    root: float
    """
    מציין אחוזים את אחוז החומר שנמצא בסה"כ מתוך סה"כ החומר עצמו שדה ב % מ 0.00000001 עד 100%
    """


class CAS(RootModel[str]):
    root: str
    """
    מייצג מספר זיהוי לכל חומר שתואר בספרות הכימית המקצועית
    """


class TEKENEXPOSURE(RootModel[str]):
    root: str
    """
    תקן חשיפה
    """


class NIIN(RootModel[str]):
    root: str
    """
    המקט הבינלאומי של ה הבינלאומי- מקט נטו
    NIIN==NSN
    """


class MANUFACTURERPARTNUM(RootModel[str]):
    root: str
    """
    מק"ט יצרן
    """


class MANUFACTURERPARTEXT(RootModel[str]):
    root: str
    """
    תוספת מק"ט  ארוך עד 500
    """


class MANUFACTURERNUMBER(RootModel[str]):
    root: str
    """
    קוד ספק
    """


class MAINTENANCETYPE(RootModel[str]):
    root: str
    """
    סוג פעילות מחזורית (תחזוקה , כיול , טעינה , בחינה) ערכים אפשריים לשדה : 
     INSPECTION 
     CHARGING 
     CALIBRATION 
     MAINTENANCE
    EXRRAACTIVITY
    """


class CYCLE(RootModel[str]):
    root: str
    """
    תדירות בדיקה בימים
    """


class WARNING(RootModel[str]):
    root: str
    """
    התראת פעולה בימים
    """


class MAINTENANCENOTE(RootModel[str]):
    root: str
    """
    הערות לפעילויות מחזוריות
    """


class LOCATION(RootModel[str]):
    root: str
    """
    מיקום פעולה לפעילות מחזורית- נדרש ברמת פקע
    """


class INSPECTIONLOT(RootModel[str]):
    root: Annotated[str, Field(max_length=12)]
    """
    מנת ביקורת טיב
    """


class VENDORID(RootModel[str]):
    root: Annotated[str, Field(max_length=10)]
    """
    מספר ספק
    """


class EVALUATIONCODE(RootModel[str]):
    root: Annotated[str, Field(max_length=1)]
    """
    קוד הערכה
    """


class CUSTOMERID(RootModel[str]):
    root: Annotated[str, Field(max_length=10)]
    """
    קוד לקוח
    """


class CUSTOMERNAME(RootModel[str]):
    root: Annotated[str, Field(max_length=35)]
    """
    שם לקוח
    """


class CUSTOMERTYPE(RootModel[str]):
    root: Annotated[str, Field(max_length=4)]
    """
    סוג לקוח
    """


class CUSTOMERACCOUNTGROUP(RootModel[str]):
    root: Annotated[str, Field(max_length=4)]
    """
    קבוצת לקוח
    """


class COORDINATESWIDTH(RootModel[str]):
    root: Annotated[str, Field(max_length=18)]
    """
    קורדינטת רוחב
    """


class COORDINATESLENGTH(RootModel[str]):
    root: Annotated[str, Field(max_length=18)]
    """
    קורדינת אורך
    """


class TRANSPORTIONZONE(RootModel[str]):
    root: Annotated[str, Field(max_length=20)]
    """
    אזור הובלה
    """


class STORAGELOCATION(RootModel[str]):
    root: Annotated[str, Field(max_length=4)]
    """
    אתר אחסון תחת הלקוח
    """


class STORAGELOCATIONTYPE(RootModel[str]):
    root: Annotated[str, Field(max_length=2)]
    """
    סוג אתר אחסון תחת הלקוח
    """


class STORAGELOCATIONTYPEDESC(RootModel[str]):
    root: Annotated[str, Field(max_length=30)]
    """
    תיאור סוג האתר אחסון
    """


class VENDORNAME(RootModel[str]):
    root: Annotated[str, Field(max_length=35)]
    """
    שם ספק
    """


class VENDORTYPE(RootModel[str]):
    root: Annotated[str, Field(max_length=2)]
    """
    סוג ספק
    """


class VENDORACCOUNTGROUP(RootModel[str]):
    root: Annotated[str, Field(max_length=4)]
    """
    קבוצת ספק
    """


class LANGUAGE(RootModel[str]):
    root: Annotated[str, Field(max_length=2)]
    """
    שפה
    """


class COUNTRY(RootModel[str]):
    root: Annotated[str, Field(max_length=3)]
    """
    ארץ
    """


class CITY(RootModel[str]):
    root: Annotated[str, Field(max_length=35)]
    """
    עיר
    """


class ADDRESS(RootModel[str]):
    root: Annotated[str, Field(max_length=35)]
    """
    כתובת
    """


class TELEPHONE1(RootModel[str]):
    root: Annotated[str, Field(max_length=16)]
    """
    טלפון 1
    """


class TELEPHONE2(RootModel[str]):
    root: Annotated[str, Field(max_length=16)]
    """
    טלפון 2
    """


class EMAIL(RootModel[str]):
    root: Annotated[str, Field(max_length=60)]
    """
    כתובת דואר אלקטרוני
    """


class CANCELEDVENDOR(RootModel[str]):
    root: Annotated[str, Field(max_length=1)]
    """
    ספק מבוטל
    """


class BLOCKEDVENDOR(RootModel[str]):
    root: Annotated[str, Field(max_length=1)]
    """
    ספק חסום
    """


class VENDORALLBLOCK(RootModel[str]):
    root: Annotated[str, Field(max_length=1)]
    """
    ספק חסום לכל הארגונים
    """


class VENDORFAX(RootModel[str]):
    root: Annotated[str, Field(max_length=31)]
    """
    פקס של ספק
    """


class CPFIRSTNAME(RootModel[str]):
    root: Annotated[str, Field(max_length=35)]
    """
    שם פרטי של איש קשר
    """


class CPLASTNAME(RootModel[str]):
    root: Annotated[str, Field(max_length=35)]
    """
    שם משפחה של איש קשר
    """


class CPTELEPHONE(RootModel[str]):
    root: Annotated[str, Field(max_length=16)]
    """
    טלפון של איש קשר
    """


class RECDOC(RootModel[str]):
    root: Annotated[str, Field(max_length=10)]
    """
    מספר מסמך
    """


class WMSORDTP(RootModel[str]):
    root: Annotated[str, Field(max_length=3)]
    """
    סוג מסמך מקור
    """


class SHIPCON(RootModel[str]):
    root: Annotated[str, Field(max_length=2)]
    """
    סוג אספקה
    """


class SUPPRTNR(RootModel[str]):
    root: Annotated[str, Field(max_length=10)]
    """
    קוד ספק
    """


class PARTNERTYPE(RootModel[str]):
    root: Annotated[str, Field(max_length=2)]
    """
    סוג חברה
    """


class OPERCODE(RootModel[str]):
    root: Annotated[str, Field(max_length=1)]
    """
    קוד פעולה (יצירה או ביטול)
    """


class HEADERTEXT(RootModel[str]):
    root: Annotated[str, Field(max_length=255)]
    """
    הערות כותרת
    """


class RELSORD(RootModel[str]):
    root: Annotated[str, Field(max_length=20)]
    """
    מס' הוראות שחרור
    """


class BOL(RootModel[str]):
    root: Annotated[str, Field(max_length=20)]
    """
    AWB|BOL
    """


class CONTAINID(RootModel[str]):
    root: Annotated[str, Field(max_length=20)]
    """
    מספר מכולה \\פאלט
    """


class CONTAINSEALNUM(RootModel[str]):
    root: Annotated[str, Field(max_length=20)]
    """
    מספר סוגר מכולה
    """


class CONTAINTYP(RootModel[str]):
    root: Annotated[str, Field(max_length=2)]
    """
    סוג מכולה
    """


class AIRORSEAIND(RootModel[str]):
    root: Annotated[str, Field(max_length=1)]
    """
    אינד' אווירי או ימי
    """


class REQUCOORD(RootModel[str]):
    root: Annotated[str, Field(max_length=1)]
    """
    אינד' נדרש תיאום
    """


class REFDELIV(RootModel[str]):
    root: Annotated[str, Field(max_length=10)]
    """
    מספר הזמנה מקושר
    """


class RECEIVINGPLANT(RootModel[str]):
    root: Annotated[str, Field(max_length=4)]
    """
    אתר מקבל
    """


class DELIVNOTE(RootModel[str]):
    root: Annotated[str, Field(max_length=20)]
    """
    תעודת משלוח
    """


class SPED(RootModel[str]):
    root: Annotated[str, Field(max_length=20)]
    """
    ספד
    """


class ARMYMANAGED(RootModel[str]):
    root: Annotated[str, Field(max_length=1)]
    """
    קליטה למחסן המזמין (מנוהל צבאי)
    """


class PICKPOINT(RootModel[str]):
    root: Annotated[str, Field(max_length=4)]
    """
    אתר אחסון מנפק -לטובת אתר
    """


class RECDOCLINE(RootModel[str]):
    root: Annotated[str, Field(max_length=10)]
    """
    מספר שורת הזמנה (אספקה)
    """


class DELETIONINDIC(RootModel[str]):
    root: Annotated[str, Field(max_length=1)]
    """
    סמן מחיקה
    """


class MODORDER(RootModel[str]):
    root: Annotated[str, Field(max_length=10)]
    """
    מספר הזמנת מקור (SAP)
    """


class SERIALPROF(RootModel[str]):
    root: Annotated[str, Field(max_length=4)]
    """
    מזהה סיריאלי
    """


class STOCKTYPE(RootModel[str]):
    root: Annotated[str, Field(max_length=1)]
    """
    סטאטוס מלאי צפוי
    """


class RECEIVINGSTORAGELOCATION(RootModel[str]):
    root: Annotated[str, Field(max_length=4)]
    """
    אתר אחסנה מקבל
    """


class LINETEXT(RootModel[str]):
    root: Annotated[str, Field(max_length=255)]
    """
    הערות שורה
    """


class ORDERTOLERANCE(RootModel[str]):
    root: Annotated[str, Field(max_length=4)]
    """
    אחוז קליטה יתר
    """


class CROSSDOCORDER(RootModel[str]):
    root: Annotated[str, Field(max_length=10)]
    """
    הזמנת קרוס-דוק
    """


class CROSSDOCORDERLINE(RootModel[str]):
    root: Annotated[str, Field(max_length=6)]
    """
    מספר שורת הזמנת הקרוס-דוק
    """


class BATCH(RootModel[str]):
    root: Annotated[str, Field(max_length=10)]
    """
    סדרה
    """


class KITSIZE(RootModel[str]):
    root: Annotated[str, Field(max_length=7)]
    """
    גודל ערכה
    """


class INSPECTIONTYPE(RootModel[str]):
    root: Annotated[str, Field(max_length=1)]
    """
    נדרש ביקורת טיב
    """


class SAPINTERORDER(RootModel[str]):
    root: Annotated[str, Field(max_length=10)]
    """
    מספר הזמנת סאפ\\הסבה (SAP)
    """


class SAPINTERORDERLINE(RootModel[str]):
    root: Annotated[str, Field(max_length=6)]
    """
    (SAP) מספר שורת הזמנת סאפ\\הסבה
    """


class MILSTRIP(RootModel[str]):
    root: Annotated[str, Field(max_length=14)]
    """
    מספר מילסטריפ
    """


class MLSTRPSPLIT(RootModel[str]):
    root: Annotated[str, Field(max_length=1)]
    """
    פיצול מילסטריפ
    """


class LOT(RootModel[str]):
    root: Annotated[str, Field(max_length=8)]
    """
    לוט
    """


class RESERVATIONORDER(RootModel[str]):
    root: Annotated[str, Field(max_length=10)]
    """
    מספר הזמנת שריון
    """


class RECEIPT(RootModel[str]):
    root: Annotated[str, Field(max_length=20)]
    """
    מספר תעודת קליטה
    """


class RECEIPTLINE(RootModel[str]):
    root: Annotated[str, Field(max_length=7)]
    """
    שורה תעודת קליטה
    """


class CONTACTPERSONNAME(RootModel[str]):
    root: Annotated[str, Field(max_length=35)]
    """
    שם איש קשר
    """


class CONTACTPERSONPHONE(RootModel[str]):
    root: Annotated[str, Field(max_length=10)]
    """
    מספר טלפון של איש הקשר
    """


class SERIAL(RootModel[str]):
    root: Annotated[str, Field(max_length=18)]
    """
    מספר סיריאלי
    """


class ASNMAINTENANCEDATE(RootModel[str]):
    root: Annotated[str, Field(max_length=8)]
    """
    תאריך תחזוקה
    """


class ASNLASTCNTDATE(RootModel[str]):
    root: Annotated[str, Field(max_length=8)]
    """
    תאריך ספירה אחרון
    """


class ASNINSPECTIONDATE(RootModel[str]):
    root: Annotated[str, Field(max_length=8)]
    """
    תאריך ביקורת איכות אחרון
    """


class ASNLOADID(RootModel[str]):
    root: Annotated[str, Field(max_length=20)]
    """
    מטען
    """


class ASNEXPIRATIONDATE(RootModel[str]):
    root: Annotated[str, Field(max_length=8)]
    """
    תאריך פג תוקף(ללא סידרה)
    """


class ASNHU(RootModel[str]):
    root: Annotated[str, Field(max_length=20)]
    """
    יחידת ניטול
    """


class ASNSKUWMS(RootModel[str]):
    root: Annotated[str, Field(max_length=100)]
    """
    מק"ט WMS פנימי
    """


class ASNCOLDATE(RootModel[str]):
    root: Annotated[str, Field(max_length=8)]
    """
    תאריך כיול
    """


class ASNCHARGEDATE(RootModel[str]):
    root: Annotated[str, Field(max_length=8)]
    """
    תאריך טעינה
    """


class ASNEXTRAACTIVITYDATE(RootModel[str]):
    root: Annotated[str, Field(max_length=8)]
    """
    תאריך פעילות נוספת
    """


class ASNALLOWPICK(RootModel[str]):
    root: Annotated[str, Field(max_length=1)]
    """
    כשיר אחזקתי לניפוק
    """


class ASNVERSION(RootModel[str]):
    root: Annotated[str, Field(max_length=50)]
    """
    גירסה
    """


class ASNVERSIONDATE(RootModel[str]):
    root: Annotated[str, Field(max_length=8)]
    """
    תאריך צריבת גירסה
    """


class ASNLOADUM(RootModel[str]):
    root: Annotated[str, Field(max_length=10)]
    """
    יחידת המידה של המטען
    """


class ASNUMUNITS(RootModel[str]):
    root: Annotated[str, Field(max_length=17)]
    """
    כמות ביחידת המידה של המטען
    """


class ASNWMSSTAT(RootModel[str]):
    root: Annotated[str, Field(max_length=10)]
    """
    סטאטוס מלאי WMS
    """


class ASNBLOCK(RootModel[str]):
    root: Annotated[str, Field(max_length=10)]
    """
    קוד סיבה חסימה
    """


class ASNHUTYPE(RootModel[str]):
    root: Annotated[str, Field(max_length=10)]
    """
    סוג יחידת ניטול
    """


class ASNKITORDER(RootModel[str]):
    root: Annotated[str, Field(max_length=7)]
    """
    סדר בערכה
    """


class ASNSUBKIT(RootModel[str]):
    root: Annotated[str, Field(max_length=20)]
    """
    תת ערכה
    """


class DOCUMENTCATEGORY(RootModel[str]):
    root: Annotated[str, Field(max_length=2)]
    """
    סוג מסמך מקור
    """


class SAPDOCUMENTTYPE(RootModel[str]):
    root: Annotated[str, Field(max_length=4)]
    """
    סוג מסמך הקוד ב SAP (לא חובה) (סוג אובייקט מקור מה SAP )
    """


class REFDOCNUM(RootModel[str]):
    root: Annotated[str, Field(max_length=10)]
    """
    מספר הזמנת מקור (SAP) (עבור החזרה לספק)
    """


class SUPPLYINGPLANT(RootModel[str]):
    root: Annotated[str, Field(max_length=4)]
    """
    אתר מנפק
    """


class SUPPLYINGSTORAGELOCATION(RootModel[str]):
    root: Annotated[str, Field(max_length=4)]
    """
    אתר אחסון מנפק
    """


class CUSTOMER(RootModel[str]):
    root: Annotated[str, Field(max_length=10)]
    """
    לקוח מזמין
    """


class DELIVERYPRIORITY(RootModel[str]):
    root: Annotated[str, Field(max_length=2)]
    """
    עדיפות אספקה
    """


class ORDERINGCUSTOMER(RootModel[str]):
    root: Annotated[str, Field(max_length=10)]
    """
    לקוח מזמין - מקבל
    """


class TRANSITDOCKINGPLANT1(RootModel[str]):
    root: Annotated[str, Field(max_length=4)]
    """
    אתר ביניים (מרחב מפיץ)
    """


class EMERGENCYCOORDINATESWIDTH(RootModel[str]):
    root: Annotated[str, Field(max_length=18)]
    """
    נקודת נ"צ רוחב חירום
    """


class EMERGENCYCOORDINATESLENGTH(RootModel[str]):
    root: Annotated[str, Field(max_length=18)]
    """
    נקודת נ"צ אורך חירום
    """


class CROSSDOCK(RootModel[str]):
    root: Annotated[str, Field(max_length=1)]
    """
    סמן קרוסדוק
    """


class Material(RootModel[str]):
    root: Annotated[str, Field(max_length=120)]
    """
    מקט-SKU
    """


class Batch(RootModel[str]):
    root: Annotated[str, Field(max_length=10)]
    """
    סדרה(שורה)
    """


class Version(RootModel[str]):
    root: str
    """
    גירסה
    """


class QUANTITIY(RootModel[str]):
    root: Annotated[str, Field(max_length=18)]
    """
    כמות של חומר
    """


class RESERVENUM(RootModel[str]):
    root: Annotated[str, Field(max_length=10)]
    """
    מספר שריון
    """


class FOODPACKING(RootModel[str]):
    root: Annotated[str, Field(max_length=1)]
    """
    סמן מארזי מזון (הרכבת מנות מוצבים)
    """


class MESIMAASHBARATIT(RootModel[str]):
    root: Annotated[str, Field(max_length=12)]
    """
    משימה השברתית (קוד מבצע)
    """


class MANPARNOTES(RootModel[str]):
    root: Annotated[str, Field(max_length=50)]
    """
    הערות מנפ"ר למחסנאי
    """


class KOSHER(RootModel[str]):
    root: Annotated[str, Field(max_length=2)]
    """
    כושר
    """


class SERIALTYPE(RootModel[str]):
    root: Annotated[str, Field(max_length=4)]
    """
    מזהה סיראלי(מסד\\צ')
    """


class MOVEMENTTYPE(RootModel[str]):
    root: Annotated[str, Field(max_length=3)]
    """
    קוד סוג תנועה
    """


class MOVEMENTREASON(RootModel[str]):
    root: Annotated[str, Field(max_length=4)]
    """
    קוד סיבה לתנועה
    """


class WMSSTATUS(RootModel[str]):
    root: Annotated[str, Field(max_length=3)]
    """
    סטטוס זכיין
    """


class SERIALNUMBER1(RootModel[str]):
    root: Annotated[str, Field(max_length=18)]
    """
    סריאלי(שורה)
    """


class CYCLEACTIVITYTYPE(RootModel[str]):
    root: Annotated[str, Field(max_length=2)]
    """
    סוג פעילות מחזורית
    """


class CYCLEACTIVITYDATE(RootModel[str]):
    root: Annotated[str, Field(max_length=8)]
    """
    תאריך פעילות מחזורית
    """


class MAINTENANCEDATE(RootModel[str]):
    root: Annotated[str, Field(max_length=8)]
    """
    תאריך פעילות מחזורית - תחזוקה
    """


class CALIBRATIONDATE(RootModel[str]):
    root: Annotated[str, Field(max_length=8)]
    """
    תאריך פעילות מחזורית - כיול
    """


class CHARGEDATE(RootModel[str]):
    root: Annotated[str, Field(max_length=8)]
    """
    תאריך פעילות מחזורית - טעינה
    """


class EXTRAACTIVITYDATE(RootModel[str]):
    root: Annotated[str, Field(max_length=8)]
    """
    תאריך פעילות מחזורית - פעילות נוספת
    """


class ASNSUBSERIES(RootModel[str]):
    root: Annotated[str, Field(max_length=20)]


class WMSDOCTYPE(RootModel[str]):
    root: Annotated[str, Field(max_length=20)]
    """
    סוג המסמך ב WMS
    """


class SAPORDERTYPE(RootModel[str]):
    root: Annotated[str, Field(max_length=4)]
    """
    סוג המסמך\\ ההזמנה בSAP
    """


class CREATEDATE(RootModel[str]):
    root: Annotated[str, Field(max_length=8)]
    """
    תאריך יצירת המסמך ב-SAP
    """


class SOLDTO(CUSTOMER):
    pass


class ZZWMSRECEIVINGDOCUMENT(RootModel[str]):
    root: Annotated[str, Field(max_length=25)]
    """
    תעודת קליטה
    """


class ZZWMSRECEIVINGDOCITEM(RootModel[str]):
    root: Annotated[str, Field(max_length=7)]
    """
    שורה בתעודת קליטה
    """


class ORDERQTY(RootModel[str]):
    root: Annotated[str, Field(max_length=17)]
    """
    כמות בשורה לביצוע
    """


class FROMBATCH(RootModel[str]):
    root: Annotated[str, Field(max_length=10)]
    """
    הסדרה ממנה מתבצעת ההמרה
    """


class FSTKTYPE(RootModel[str]):
    root: Annotated[str, Field(max_length=1)]
    """
    סוג מלאי ממנו מתבצעת ההמרה
    """


class BATCHSTATUS(RootModel[str]):
    root: Annotated[str, Field(max_length=1)]
    """
    סטטוס הסדרה
    """


class TSTKTYPE(RootModel[str]):
    root: Annotated[str, Field(max_length=1)]
    """
    סוג מלאי
    """


class ISSUEPLANT(SUPPLYINGPLANT):
    pass


class ISSUESTLOC(RootModel[str]):
    root: Annotated[str, Field(max_length=4)]
    """
    אתר אחסון מנפק-שורה
    """


class RECEIVINGSTLOC(RootModel[str]):
    root: Annotated[str, Field(max_length=4)]
    """
    אתר אחסון מקבל-שורה
    """


class TOLERANCE(RootModel[str]):
    root: Annotated[str, Field(max_length=4)]
    """
    אחוז טולרנס
    """


class DELETIONINDICATOR(DELETIONINDIC):
    pass


class ORDERREASON(RootModel[str]):
    root: Annotated[str, Field(max_length=3)]
    """
    סיבה להזמנה
    """


class EXPIREDDATE(RootModel[str]):
    root: Annotated[str, Field(max_length=8)]
    """
    תאריך פג תוקף
    """


class TORESERVATION(RootModel[str]):
    root: Annotated[str, Field(max_length=10)]
    """
    לשריון
    """


class FROMSERIALNUMBER(RootModel[str]):
    root: Annotated[str, Field(max_length=18)]
    """
    מסד\\צ
    """


class CREATETIME(RootModel[str]):
    root: Annotated[str, Field(max_length=6)]
    """
    שעת מסמך - חותמת זמן (שעות ודקות)
    """


class ORDERNUMBER(RootModel[str]):
    root: str
    """
    מספר פקע
    """


class ENDDATE(RootModel[str]):
    root: str
    """
    תאריך סיום פקע
    """


class WMSWORKCENTER(RootModel[str]):
    root: str
    """
    גורם מטפל WMS
    """


class RECIVINGPLANT(RootModel[str]):
    root: str
    """
    אתר
    """


class ORDERINTOF(RootModel[str]):
    root: str
    """
    שורה בפקע
    """


class FROMMATERIAL(RootModel[str]):
    root: Annotated[str, Field(max_length=120)]
    """
    מק"ט ערכה
    """


class FROMORDERQTY(RootModel[str]):
    root: str
    """
    כמות ערכה
    """


class ISSUESTLOC1(RootModel[str]):
    root: str
    """
    אתר אחסון
    """


class KITLOCATION(RootModel[str]):
    root: str
    """
    מיקום פריט בערכה
    """


class RECIVINGSTLOC(ISSUESTLOC1):
    pass


class TOMATERIAL(RootModel[str]):
    root: str
    """
    מקט
    """


class TOORDERQTY(RootModel[str]):
    root: str
    """
    כמות
    """


class TOBATCH(RootModel[str]):
    root: str
    """
    סדרה
    """


class ORDERINTOT(ORDERINTOF):
    pass


class TOSERIALNUMBER(RootModel[str]):
    root: str
    """
    מסד\\צ
    """


class MATERIALTYPE1(RootModel[str]):
    root: str
    """
    סוג הפריט צהלי או ייצרן
    """


class DESCRIPTIONSHORT(RootModel[str]):
    root: str
    """
    תיאור קצר של הפריט
    """


class ITEMCLASS(RootModel[str]):
    root: str
    """
    פרופיל פריט
    """


class IMAGE(RootModel[str]):
    root: str
    """
    תמונת פריט
    """


class NEWITEM(RootModel[str]):
    root: str
    """
    מקט חדש
    """


class INITIALSTATUS(RootModel[str]):
    root: str
    """
    סטאטוס לקליטה ברירת מחדל
    """


class HUTYPE(RootModel[str]):
    root: str
    """
    סוג יחידת ניטול
    """


class DEFAULTUOM(RootModel[str]):
    root: str
    """
    יחידת מידה ברירת מחדל
    """


class DEFAULTRECUOM(RootModel[str]):
    root: str
    """
    יחידת מידה ברירת מחדל לקליטה
    """


class OVERRECEIVEPCT(RootModel[str]):
    root: str
    """
    אחוז קליטת יתר
    """


class OVERPICKPCT(RootModel[str]):
    root: str
    """
    אחוז ליקוט יתר
    """


class NOTES(RootModel[str]):
    root: str
    """
    הערות כלליות לפריט
    """


class COUNTTOLERANCE(RootModel[str]):
    root: str
    """
    פקטור בספירה להתראה
    """


class CYCLECOUNTINT(RootModel[str]):
    root: str
    """
    מספר ימים לספירה מחזורית
    """


class LOWLIMITCOUNT(RootModel[str]):
    root: str
    """
    סף מינימום לספירה
    """


class OPORTUNITYREPLFLAG(RootModel[str]):
    root: str
    """
    רענון מזדמן
    """


class STORAGECLASS(RootModel[str]):
    root: str
    """
    סוג אחסון
    """


class PICKSORTORDER(RootModel[str]):
    root: str
    """
    סדר ליקוט (מעיכות)
    """


class BASEITEM(RootModel[str]):
    root: str
    """
    פריט בסיס
    """


class PUTAWAYNOTES(RootModel[str]):
    root: str
    """
    הערות לפיזור
    """


class PACKNOTES(RootModel[str]):
    root: str
    """
    הערות לאריזה
    """


class WONOTES(RootModel[str]):
    root: str
    """
    הערות לפק"ע
    """


class RECADDITIONALWORK(RootModel[str]):
    root: str
    """
    עבודות משלימות לקבלה
    """


class KITFACTOR(RootModel[str]):
    root: str
    """
    פקטור תזמון לקיט
    """


class WEIGHTTYPE(RootModel[str]):
    root: str
    """
    סוג פריט שקיל
    """


class LINGEROUTTIME(RootModel[str]):
    root: str
    """
    זמן שהייה מחוץ לאיזור הטמפרטורה באחסון
    """


class CONFIRMSKUONPICK(RootModel[str]):
    root: str
    """
    דורש אימות פריט בליקוט
    """


class PRINTSKULBLREC(RootModel[str]):
    root: str
    """
    הפקת מדבקת פריט בקבלה
    """


class REQINSPECTIONREC(RootModel[str]):
    root: str
    """
    דורש בקרת איכות בקליטה
    """


class REQSAMPLINGREC(RootModel[str]):
    root: str
    """
    דורש לקיחת דוגמה בקבלה
    """


class SAMPLESIZE(RootModel[str]):
    root: str
    """
    גודל דוגמה
    """


class LEADITEM(RootModel[str]):
    root: str
    """
    מק"ט מקבץ
    """


class LEADITEMSIZE(RootModel[str]):
    root: str
    """
    מידה של המקט המקבץ
    """


class VELOCITYGROUP(RootModel[str]):
    root: str
    """
    קבוצת מהירות
    """


class PHARMACYINSPECTION(RootModel[str]):
    root: str
    """
    בקרת רוקח
    """


class G29(RootModel[str]):
    root: str
    """
    29 ג
    """


class WEIGHTTOLERANCEPCT(RootModel[str]):
    root: str
    """
    אחוז סטייה בשקילה
    """


class UOM(RootModel[str]):
    root: str
    """
    יחידת המידה
    """


class EANUPC(RootModel[str]):
    root: str
    """
    ברקוד אריזה
    """


class BRGEW(RootModel[str]):
    root: str
    """
    משקל ברוטו
    """


class NTGEW(RootModel[str]):
    root: str
    """
    משקל נטו
    """


class LAENG(RootModel[str]):
    root: str
    """
    אורך
    """


class BREIT(RootModel[str]):
    root: str
    """
    רוחב
    """


class HOEHE(RootModel[str]):
    root: str
    """
    גובה
    """


class VOLUME(RootModel[str]):
    root: str
    """
    נפח
    """


class MEABM(RootModel[str]):
    root: str
    """
    יחידת מידה לייחוס
    """


class SHIPPABLE(RootModel[str]):
    root: str
    """
    ניתן לשילוח
    """


class SKU(UNENDESC):
    pass


class UNITPERLOWESTUOM(UNENDESC):
    pass


class PACKAGETYPE(RootModel[str]):
    root: str
    """
    סוג חבילה
    """


class GRABTYPE(RootModel[str]):
    root: str
    """
    סוג אריזה
    """


class CASEPREPARATIONTYPE(RootModel[str]):
    root: str
    """
    סוג הכנת מארז
    """


class EACHHANDLINGTYPE(RootModel[str]):
    root: str
    """
    כלי ניטול פריט
    """


class LABORPACKAGETYPE(RootModel[str]):
    root: str
    """
    סוג אריזה לביצוע עבודה
    """


class LABORGRABTYPE(RootModel[str]):
    root: str
    """
    סוג לקיחה לביצוע עבודה
    """


class LABORPREPARATIONTYPE(RootModel[str]):
    root: str
    """
    סוג הכנה לביצוע עבודה
    """


class LABORHANDLINGTYPE(RootModel[str]):
    root: str
    """
    סוג שינוע לביצוע עבודה
    """


class VERSIONDESC(LABORHANDLINGTYPE):
    pass


class KITTYPE(RootModel[str]):
    root: str
    """
    סוג ערכה (אופן ניהול הערכה בסדרה חד-חד-ערכי/ כמותי/ חד-חד-ערכי יחידני/ חד-חד-ערכי מאוחד).
    """


class RECEIPTTYPE(RootModel[str]):
    root: Annotated[str, Field(max_length=2)]
    """
    סוג קליטה
    """


class QTY(RootModel[str]):
    root: Annotated[str, Field(max_length=17)]
    """
    כמות HU שהתקבלה
    """


class INCPECTIONNUM(RootModel[str]):
    root: Annotated[str, Field(max_length=25)]
    """
    תעודת בחינה
    """


class WAREHOUSEID(RootModel[str]):
    root: Annotated[str, Field(max_length=10)]
    """
    מספר מחסן יעד
    """


class PRODDATE(RootModel[str]):
    root: Annotated[str, Field(max_length=8)]
    """
    תאריך ייצור
    """


class VENDOREXPDATE(RootModel[str]):
    root: Annotated[str, Field(max_length=8)]
    """
    תפוגת ספק
    """


class PURPOSEKIT(RootModel[str]):
    root: Annotated[str, Field(max_length=2)]
    """
    ייעוד הערכה
    """


class PASSKOSHER(RootModel[str]):
    root: Annotated[str, Field(max_length=2)]
    """
    כשר/לא כשר לפסח
    """


class AppointmentID(RootModel[str]):
    root: str
    """
    מספר הזימון
    """


class Status(RootModel[str]):
    root: str
    """
    סטאטוס הזימון (מאושר/מאושר)
    """


class ReasonCode(RootModel[str]):
    root: str
    """
    קוד סיבת דחייה
    """


class Notes(RootModel[str]):
    root: str
    """
    הערות
    """


class VehicleID(RootModel[str]):
    root: str
    """
    מספר הרכב
    """


class Gate(RootModel[str]):
    root: str
    """
    מספר שער
    """


class MovementType(RootModel[str]):
    root: str
    """
    סוג תנועה
    """


class TimeOfMovement(RootModel[str]):
    root: str
    """
    מועד התנועה בשער
    """


class APPOITMENTID(RootModel[str]):
    root: str
    """
    מספר זימון
    """


class SCHEDULEDATE(RootModel[str]):
    root: str
    """
    תאריך זימון
    """


class FROMTIME(RootModel[str]):
    root: str
    """
    שעת תחילת זימון
    """


class TOTIME(RootModel[str]):
    root: str
    """
    שעת סיום זימון
    """


class DOCUMENTNUM(RootModel[str]):
    root: str
    """
    מספר מסמך SAP
    """


class DOCUMENTITEM(RootModel[str]):
    root: Annotated[str, Field(max_length=5)]
    """
    מספר שורה SAP
    """


class WMSCERTIFICATE(RootModel[str]):
    root: str
    """
    מספר מסמך WMS
    """


class WMSCERTIFICATEITEM(RootModel[str]):
    root: str
    """
    מספר שורה מסמך WMS
    """


class DISTRIBUTIONROUTE(RootModel[str]):
    root: Annotated[str, Field(max_length=20)]
    """
    מספר מסלול
    """


class DISTRIBUTIONDATE(RootModel[str]):
    root: Annotated[str, Field(max_length=8)]
    """
    תאריך הפצה
    """


class DOCUMENTTYPESAP(RootModel[str]):
    root: Annotated[str, Field(max_length=2)]
    """
    סוג מסמך
    """


class ORDERID(RootModel[str]):
    root: Annotated[str, Field(max_length=20)]
    """
    מספר תעודת יציאה
    """


class CHANGEDATE(RootModel[str]):
    root: Annotated[str, Field(max_length=8)]
    """
    תאריך עדכון/יצירה
    """


class RESTRICTED(BATCHSTATUS):
    pass


class NEXTINSPEC(RootModel[str]):
    root: Annotated[str, Field(max_length=8)]
    """
    תאריך ביקורת איכות
    """


class VENDORBATCH(RootModel[str]):
    root: Annotated[str, Field(max_length=15)]
    """
    סדרת ספק
    """


class DATE1(RootModel[str]):
    root: Annotated[str, Field(max_length=8)]
    """
    תאריך ביקורת דלק
    """


class DATE2(DATE1):
    pass


class DATE3(DATE1):
    pass


class DATE5(RootModel[str]):
    root: Annotated[str, Field(max_length=8)]
    """
    תאריך 5
    """


class DATE6(RootModel[str]):
    root: Annotated[str, Field(max_length=8)]
    """
    תאריך 6
    """


class STATUSON(RootModel[str]):
    root: Annotated[str, Field(max_length=1)]
    """
    סטטוס חסימה
    """


class InterfaceName(RootModel[str]):
    root: Annotated[
        str,
        Field(
            examples=['ZWMS_WMS_PULL_PUSH_UNIT', 'ZWMS_WMS_RETURN_UNIT'],
            max_length=41,
            min_length=4,
            pattern='^Z[A-Z0-9_]{3,40}$',
        ),
    ]
    """
    SAP WMS interface routing key. Always begins with 'Z' (custom namespace), uppercase alphanumeric + underscore. Strictly pattern-checked — unknown interfaces are hard-rejected. Analogous to message_type in the generic firewall.
    """


class MessageId(RootModel[str]):
    root: Annotated[
        str,
        Field(
            examples=['0000002243643973', '0000000000000001'],
            max_length=16,
            min_length=16,
            pattern='^[0-9]{16}$',
        ),
    ]
    """
    Unique 16-digit zero-padded message identifier assigned by the sending system.
    """


class PlantCode(RootModel[str]):
    root: Annotated[
        str,
        Field(
            examples=['6300', '0010', '1000'],
            max_length=4,
            min_length=4,
            pattern='^[0-9]{4}$',
        ),
    ]
    """
    SAP 4-digit numeric plant code. Infrastructure primitive — owned by the infra/master-data team. Declared once here; $ref'd by any payload field that carries a plant code (SUPPLYING_PLANT, RECEIVING_PLANT, TRANSIT_DOCKING_PLANT).
    """


class ConsigneeCode(RootModel[str]):
    root: Annotated[
        str,
        Field(
            examples=['ATAL', 'MAIN', 'WH01'],
            max_length=10,
            min_length=2,
            pattern='^[A-Z0-9]{2,10}$',
        ),
    ]
    """
    Recipient/consignee short code. Uppercase alphanumeric, 2–10 chars. Infrastructure-level recipient identity — not a business-domain customer identifier.
    """


class SapDate(RootModel[str]):
    root: Annotated[
        str,
        Field(
            examples=['20240915', '20241010'],
            max_length=8,
            min_length=8,
            pattern='^[0-9]{8}$',
        ),
    ]
    """
    SAP compact date format YYYYMMDD. Used for all date fields across envelope and payload. Declared once here; $ref'd by payload date fields (DELIVERY_DATE etc.).
    """


class SapTime(RootModel[str]):
    root: Annotated[
        str,
        Field(
            examples=['160656', '083000', '235959'],
            max_length=6,
            min_length=6,
            pattern='^[0-9]{6}$',
        ),
    ]
    """
    SAP compact time format HHMMSS (24-hour). Used in envelope timestamp; payload systems may $ref for time fields.
    """


class OpaqueDocHeader(BaseModel):
    """
    Business document payload. INTENTIONALLY OPAQUE to the firewall. Structure varies by WMS_ORD_TP order type. The recipient/WMS system is the sole owner of DOC_HEADER validation (Layer 2).
    """

    model_config = ConfigDict(
        extra='allow',
    )


class BatchSplit(BaseModel):
    """
    A portion of a line item fulfilled from one specific batch. Used when a single delivery line is split across multiple batches (e.g. partial FIFO fulfilment).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    BATCH: Annotated[str, Field(max_length=10, min_length=1)]
    """
    Batch/lot number for this split.
    """
    QUANTITY: SapQuantity
    STOCK_TYPE: Annotated[str | None, Field(max_length=2)] = None
    STORAGE_LOCATION: StorageLocation | None = None
    SHELF_LIFE_EXP_DATE: SHELFLIFEEXPDATE | SapDate | None = None


class QualityInspection(BaseModel):
    """
    Quality inspection block attached to a document item. Present only for Q-inspection managed materials. Contains the inspection lot reference, usage decision, and an array of evaluated characteristics (each an InspectionCharacteristic dict).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    INSPECTION_LOT: Annotated[str, Field(pattern='^[0-9]{12}$')]
    """
    12-digit SAP inspection lot number assigned at goods receipt.
    """
    USAGE_DECISION: QualityDecision
    INSPECTOR_ID: Annotated[str | None, Field(max_length=12)] = None
    """
    SAP user ID of the inspector who posted the usage decision.
    """
    INSPECTION_DATE: SapDate | None = None
    CHARACTERISTICS: Annotated[
        list[InspectionCharacteristic], Field(max_length=50, min_length=1)
    ]
    """
    Array of quality characteristics evaluated during inspection. Each entry is an InspectionCharacteristic dict.
    """


class DocItem(BaseModel):
    """
    A single WMS document line item. Open schema (no additionalProperties:false) — SAP custom Z-fields and extension fields are common and must not be rejected by schema drift. Nested fields: BATCH_SPLITS (array of dicts), HANDLING_UNITS (array of dicts with nested DIMENSIONS + ITEMS), QUALITY_INSPECTION (object with CHARACTERISTICS array), SERIAL_NUMBERS (array of strings), CUSTOM_FIELDS (dict).
    """

    DELIVERY_DATE: SapDate
    SUPPLYING_STORAGE_LOCATION: StorageLocation
    CUSTOMER: Annotated[str | None, Field(max_length=10)] = None
    CUSTOMER_TYPE: TwoDigitCode | None = None
    RECEIVING_PLANT: PlantCode
    RECEIVING_STORAGE_LOCATION: StorageLocation
    DELIVERY_PRIORITY: TwoDigitCode | None = None
    SHIP_CON: TwoDigitCode | None = None
    ORDERING_CUSTOMER: CustomerNumber
    CONTACT_PERSON_NAME: Annotated[str | None, Field(max_length=100)] = None
    CONTACT_PERSON_PHONE: Annotated[str | None, Field(max_length=30)] = None
    TRANSIT_DOCKING_PLANT: TRANSITDOCKINGPLANT | PlantCode | None = None
    COORDINATES_WIDTH: CoordinateDecimal | None = None
    COORDINATES_LENGTH: CoordinateDecimal | None = None
    DOCUMENT_ITEM_SAP: SapItemNumber
    DELETION_INDIC: Annotated[str | None, Field(max_length=1)] = None
    CROSS_DOCK: Annotated[str | None, Field(max_length=1)] = None
    MATERIAL: MaterialNumber
    BATCH: Annotated[str | None, Field(max_length=10)] = None
    QUANTITY: SapQuantity
    STOCK_TYPE: Annotated[str | None, Field(max_length=2)] = None
    RESERVE_NUM: Annotated[str | None, Field(max_length=16)] = None
    VERSION: Annotated[str | None, Field(max_length=20)] = None
    FOOD_PACKING: Annotated[str | None, Field(max_length=1)] = None
    EMERGENCY_TIME_ISSUE: Annotated[str | None, Field(max_length=1)] = None
    MILITARY_ZACHYAN_MANAGMENT: Annotated[str | None, Field(max_length=1)] = None
    MESIMA_ASHBARATIT: Annotated[str | None, Field(max_length=20)] = None
    MANPAR_NOTES: Annotated[str | None, Field(max_length=100)] = None
    SERIAL_TYPE: Annotated[str | None, Field(max_length=4)] = None
    MOVMENT_TYPE: Annotated[str | None, Field(max_length=3)] = None
    REASON_FOR_MOVMENT: Annotated[str | None, Field(max_length=4)] = None
    WMS_STATUS: Annotated[str | None, Field(max_length=4)] = None
    SERIAL_NUMBERS: Annotated[list[SerialNumber] | None, Field(max_length=999)] = None
    """
    Array of serial numbers for serial-number managed materials. Length must not exceed QUANTITY. Omit entirely for non-serialized materials.
    """
    BATCH_SPLITS: Annotated[
        list[BatchSplit] | None, Field(max_length=50, min_length=2)
    ] = None
    """
    Array of batch split dicts. Present when a single line item is fulfilled from multiple batches. Sum of quantities across splits should equal item QUANTITY. Each split is a BatchSplit object: { BATCH, QUANTITY, STOCK_TYPE?, STORAGE_LOCATION?, SHELF_LIFE_EXP_DATE? }.
    """
    HANDLING_UNITS: Annotated[
        list[HandlingUnit] | None, Field(max_length=100, min_length=1)
    ] = None
    """
    Array of handling unit dicts describing the physical packaging of this line item. Each HandlingUnit has: HU_NUMBER, HU_TYPE, weights, DIMENSIONS (nested object: LENGTH/WIDTH/HEIGHT/UNIT), and ITEMS (nested array of HuItem dicts: MATERIAL/BATCH/QUANTITY/SERIAL_NUMBER).
    """
    QUALITY_INSPECTION: QualityInspection | None = None
    CUSTOM_FIELDS: dict[str, str] | None = None
    """
    Arbitrary SAP Z-field extension bag. Keys are field names (convention: ZCUSTOM_*), values are raw SAP string values. Open dict — no fixed property list. Allows any implementation-specific Z-fields without a schema update.
    """


class UsageDecisionBlock(BaseModel):
    """
    Quality usage decision block. Encapsulates the final SAP usage decision for an inspection lot: decision code, inspector, date, and optional remarks. Promoted from per-interface inline definition to BT so all schemas share one canonical type.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    DECISION: QualityDecision
    """
    Decision code: A=Accept, R=Reject, P=Partial, N=Not yet decided.
    """
    INSPECTOR_ID: Annotated[str, Field(max_length=12)]
    """
    SAP user ID of the inspector who posted the usage decision.
    """
    DECISION_DATE: SapDate | None = None
    REMARKS: Annotated[str | None, Field(max_length=255)] = None
