# generated by datamodel-codegen:
#   filename:  envelope.schema.json
#   timestamp: 2026-04-09T22:23:29+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, RootModel


class InterfaceName(RootModel[str]):
    root: Annotated[
        str,
        Field(
            examples=['ZWMS_WMS_PULL_PUSH_UNIT', 'ZWMS_WMS_RETURN_UNIT'],
            max_length=41,
            min_length=4,
            pattern='^Z[A-Z0-9_]{3,40}$',
        ),
    ]
    """
    SAP WMS interface routing key. Always begins with 'Z' (custom namespace), uppercase alphanumeric + underscore. Strictly pattern-checked — unknown interfaces are hard-rejected. Analogous to message_type in the generic firewall.
    """


class MessageId(RootModel[str]):
    root: Annotated[
        str,
        Field(
            examples=['0000002243643973', '0000000000000001'],
            max_length=16,
            min_length=16,
            pattern='^[0-9]{16}$',
        ),
    ]
    """
    Unique 16-digit zero-padded message identifier assigned by the sending system.
    """


class PlantCode(RootModel[str]):
    root: Annotated[
        str,
        Field(
            examples=['6300', '0010', '1000'],
            max_length=4,
            min_length=4,
            pattern='^[0-9]{4}$',
        ),
    ]
    """
    SAP 4-digit numeric plant code. Infrastructure primitive — owned by the infra/master-data team. Declared once here; $ref'd by any payload field that carries a plant code (SUPPLYING_PLANT, RECEIVING_PLANT, TRANSIT_DOCKING_PLANT).
    """


class ConsigneeCode(RootModel[str]):
    root: Annotated[
        str,
        Field(
            examples=['ATAL', 'MAIN', 'WH01'],
            max_length=10,
            min_length=2,
            pattern='^[A-Z0-9]{2,10}$',
        ),
    ]
    """
    Recipient/consignee short code. Uppercase alphanumeric, 2–10 chars. Infrastructure-level recipient identity — not a business-domain customer identifier.
    """


class SapDate(RootModel[str]):
    root: Annotated[
        str,
        Field(
            examples=['20240915', '20241010'],
            max_length=8,
            min_length=8,
            pattern='^[0-9]{8}$',
        ),
    ]
    """
    SAP compact date format YYYYMMDD. Used for all date fields across envelope and payload. Declared once here; $ref'd by payload date fields (DELIVERY_DATE etc.).
    """


class SapTime(RootModel[str]):
    root: Annotated[
        str,
        Field(
            examples=['160656', '083000', '235959'],
            max_length=6,
            min_length=6,
            pattern='^[0-9]{6}$',
        ),
    ]
    """
    SAP compact time format HHMMSS (24-hour). Used in envelope timestamp; payload systems may $ref for time fields.
    """


class OpaqueDocHeader(BaseModel):
    """
    Business document payload. INTENTIONALLY OPAQUE to the firewall. Structure varies by WMS_ORD_TP order type. The recipient/WMS system is the sole owner of DOC_HEADER validation (Layer 2).
    """

    model_config = ConfigDict(
        extra='allow',
    )


class Header(BaseModel):
    """
    Message envelope. All 6 fields are infrastructure invariants validated by the firewall.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    INTERFACE_NAME: InterfaceName
    ID: MessageId
    PLANT: PlantCode
    DATE: SapDate
    TIME: SapTime
    CONSIGNEE: ConsigneeCode


class WmsEnvelope(BaseModel):
    """
    Layer 1 — stable WMS message envelope. Owned by the security/infrastructure team. Validates the Header block only. DOC_HEADER is intentionally opaque: format never changes with business requirements; business content never belongs here.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    Header_1: Annotated[Header, Field(alias='Header')]
    """
    Message envelope. All 6 fields are infrastructure invariants validated by the firewall.
    """
    DOC_HEADER: OpaqueDocHeader
