# generated by datamodel-codegen:
#   filename:  ZWMS_INBOUND_DELIVERY_CREATE.schema.json
#   timestamp: 2026-04-09T22:23:29+00:00

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import AfterValidator, BaseModel, ConfigDict, Field, RootModel

from . import business_types_schema


class Header(BaseModel):
    """
    Message envelope. All 6 fields are infrastructure invariants validated by the firewall.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    INTERFACE_NAME: Literal['ZWMS_INBOUND_DELIVERY_CREATE']


class InterfaceName(RootModel[str]):
    root: Annotated[
        str,
        Field(
            examples=['ZWMS_WMS_PULL_PUSH_UNIT', 'ZWMS_WMS_RETURN_UNIT'],
            max_length=41,
            min_length=4,
            pattern='^Z[A-Z0-9_]{3,40}$',
        ),
    ]
    """
    SAP WMS interface routing key. Always begins with 'Z' (custom namespace), uppercase alphanumeric + underscore.
    Strictly pattern-checked — unknown interfaces are hard-rejected. Analogous to message_type in the generic firewall.
    """


class MessageId(RootModel[str]):
    root: Annotated[
        str,
        Field(
            examples=['0000002243643973', '0000000000000001'],
            max_length=16,
            min_length=16,
            pattern='^[0-9]{16}$',
        ),
    ]
    """
    Unique 16-digit zero-padded message identifier assigned by the sending system.
    """


class PlantCode(RootModel[str]):
    root: Annotated[
        str,
        Field(
            examples=['6300', '0010', '1000'],
            max_length=4,
            min_length=4,
            pattern='^[0-9]{4}$',
        ),
    ]
    """
    SAP 4-digit numeric plant code. Infrastructure primitive — owned by the infra/master-data team. Declared once
    here; $ref'd by any payload field that carries a plant code (SUPPLYING_PLANT, RECEIVING_PLANT,
    TRANSIT_DOCKING_PLANT).
    """


class ConsigneeCode(RootModel[str]):
    root: Annotated[
        str,
        Field(
            examples=['ATAL', 'MAIN', 'WH01'],
            max_length=10,
            min_length=2,
            pattern='^[A-Z0-9]{2,10}$',
        ),
    ]
    """
    Recipient/consignee short code. Uppercase alphanumeric, 2–10 chars. Infrastructure-level recipient identity — not
    a business-domain customer identifier.
    """


class SapDate(RootModel[str]):
    root: Annotated[
        str,
        Field(
            examples=['20240915', '20241010'],
            max_length=8,
            min_length=8,
            pattern='^[0-9]{8}$',
        ),
    ]
    """
    SAP compact date format YYYYMMDD. Used for all date fields across envelope and payload. Declared once here;
    $ref'd by payload date fields (DELIVERY_DATE etc.).
    """


class SapTime(RootModel[str]):
    root: Annotated[
        str,
        Field(
            examples=['160656', '083000', '235959'],
            max_length=6,
            min_length=6,
            pattern='^[0-9]{6}$',
        ),
    ]
    """
    SAP compact time format HHMMSS (24-hour). Used in envelope timestamp; payload systems may $ref for time fields.
    """


class OpaqueDocHeader(BaseModel):
    """
    Business document payload. INTENTIONALLY OPAQUE to the firewall. Structure varies by WMS_ORD_TP order type. The
    recipient/WMS system is the sole owner of DOC_HEADER validation (Layer 2).
    """

    model_config = ConfigDict(
        extra='allow',
    )


class InboundDocItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )

    # --- Required ---
    MATERIAL                  : business_types_schema.MaterialNumber
    QUANTITY                  : business_types_schema.SapQuantity
    RECEIVING_STORAGE_LOCATION: business_types_schema.StorageLocation

    # --- Optional ---
    BATCH             : Annotated[str, Field(max_length=10)] | None = None
    STOCK_TYPE        : Annotated[str, Field(max_length=2)]  | None = None
    DELIVERY_DATE     : SapDate                              | None = None
    LINE_TEXT         : Annotated[str, Field(max_length=40)] | None = None
    DELETION_INDIC    : Annotated[str, Field(max_length= 1)] | None = None
    INSPECTION_TYPE   : Annotated[str, Field(max_length= 2)] | None = None
    MILSTRIP          : Annotated[str, Field(max_length=20)] | None = None
    LOT               : Annotated[str, Field(max_length=10)] | None = None
    
    QUALITY_INSPECTION: business_types_schema.QualityInspection | None = None
    
    HANDLING_UNITS: Annotated[
        list[business_types_schema.HandlingUnit],
        Field(max_length=100, min_length=1),
    ] | None = None
    SERIAL_NUMBERS: Annotated[
        list[business_types_schema.SerialNumber] | None,
        Field(max_length=999, json_schema_extra={"uniqueItems": True}),
        AfterValidator(business_types_schema._unique_items),
    ] = None
    BATCH_SPLITS: Annotated[
        list[business_types_schema.BatchSplit],
        Field(max_length=50, min_length=2),
    ] | None = None


class Body(BaseModel):
    """
    Payload schema for sheet '5,6,7,8,24.1' – קבלה למלאי (אספקה נכנסת) רכש מקומי (Outbound)
    """

    model_config = ConfigDict(
        extra='forbid',
    )

    # --- Required ---
    REC_DOC          : business_types_schema.RECDOC
    WMS_ORD_TP       : business_types_schema.WMSORDTP
    SUP_PRTNR        : business_types_schema.SUPPRTNR
    RECEIVING_PLANT  : business_types_schema.RECEIVINGPLANT
    DELIVERY_DATE    : SapDate
    DOC_ITEM         : Annotated[list[InboundDocItem], Field(max_length=999, min_length=1)]

    # --- Optional ---
    SHIP_CON                  : business_types_schema.SHIPCON                              | None = None
    PARTNER_TYPE              : business_types_schema.PARTNERTYPE                          | None = None
    OPER_CODE                 : business_types_schema.OPERCODE                             | None = None
    HEADER_TEXT               : business_types_schema.HEADERTEXT                           | None = None
    RELS_ORD                  : business_types_schema.RELSORD                              | None = None
    BOL_1                     : Annotated[business_types_schema.BOL | None, Field(alias='BOL')] = None
    CONTAIN_ID                : business_types_schema.CONTAINID                            | None = None
    CONTAIN_SEAL_NUM          : business_types_schema.CONTAINSEALNUM                       | None = None
    CONTAIN_TYP               : business_types_schema.CONTAINTYP                           | None = None
    AIR_OR_SEA_IND            : business_types_schema.AIRORSEAIND                          | None = None
    REQU_COORD                : business_types_schema.REQUCOORD                            | None = None
    REF_DELIV                 : business_types_schema.REFDELIV                             | None = None
    DELIV_NOTE                : business_types_schema.DELIVNOTE                            | None = None
    SPED_1                    : Annotated[business_types_schema.SPED | None, Field(alias='SPED')] = None
    ARMY_MANAGED              : business_types_schema.ARMYMANAGED                          | None = None
    PICK_POINT                : business_types_schema.PICKPOINT                            | None = None
    REC_DOC_LINE              : business_types_schema.RECDOCLINE                           | None = None
    DELETION_INDIC            : business_types_schema.DELETIONINDIC                        | None = None
    MOD_ORDER                 : business_types_schema.MODORDER                             | None = None
    MATERIAL                  : business_types_schema.MaterialNumber                       | None = None
    SERIAL_PROF               : business_types_schema.SERIALPROF                           | None = None
    QUANTITY                  : business_types_schema.SapQuantity                          | None = None
    STOCK_TYPE                : business_types_schema.STOCKTYPE                            | None = None
    RECEIVING_STORAGE_LOCATION: business_types_schema.RECEIVINGSTORAGELOCATION             | None = None
    LINE_TEXT                 : business_types_schema.LINETEXT                             | None = None
    ORDER_TOLERANCE           : business_types_schema.ORDERTOLERANCE                       | None = None
    CROSS_DOC_ORDER           : business_types_schema.CROSSDOCORDER                        | None = None
    CROSS_DOC_ORDER_LINE      : business_types_schema.CROSSDOCORDERLINE                    | None = None
    BATCH_1                   : Annotated[business_types_schema.BATCH | None, Field(alias='BATCH')] = None
    KIT_SIZE                  : business_types_schema.KITSIZE | None = None
    INSPECTION_TYPE           : business_types_schema.INSPECTIONTYPE | None = None
    SAP_INTER_ORDER           : business_types_schema.SAPINTERORDER | None = None
    SAP_INTER_ORDER_LINE      : business_types_schema.SAPINTERORDERLINE | None = None
    MILSTRIP_1                : Annotated[business_types_schema.MILSTRIP | None, Field(alias='MILSTRIP')] = None
    MLSTRP_SPLIT              : business_types_schema.MLSTRPSPLIT | None = None
    LOT_1                     : Annotated[business_types_schema.LOT | None, Field(alias='LOT')] = None
    RESERVATION_ORDER         : business_types_schema.RESERVATIONORDER | None = None
    RECEIPT_1                 : Annotated[business_types_schema.RECEIPT | None, Field(alias='RECEIPT')] = None
    RECEIPT_LINE              : business_types_schema.RECEIPTLINE | None = None
    CONTACT_PERSON_NAME       : business_types_schema.CONTACTPERSONNAME | None = None
    CONTACT_PERSON_PHONE      : business_types_schema.CONTACTPERSONPHONE | None = None
    COORDINATES_WIDTH         : business_types_schema.COORDINATESWIDTH | None = None
    COORDINATES_LENGTH        : business_types_schema.COORDINATESLENGTH | None = None
    SERIAL_1                  : Annotated[business_types_schema.SERIAL | None, Field(alias='SERIAL')] = None
    ASN_MAINTENANCE_DATE      : business_types_schema.ASNMAINTENANCEDATE | None = None
    ASN_LAST_CNT_DATE         : business_types_schema.ASNLASTCNTDATE | None = None
    ASN_INSPECTION_DATE       : business_types_schema.ASNINSPECTIONDATE | None = None
    ASN_LOADID                : business_types_schema.ASNLOADID | None = None
    ASN_EXPIRATION_DATE       : business_types_schema.ASNEXPIRATIONDATE | None = None
    ASN_HU                    : business_types_schema.ASNHU | None = None
    ASN_SKU_WMS               : business_types_schema.ASNSKUWMS | None = None
    ASN_COL_DATE              : business_types_schema.ASNCOLDATE | None = None
    ASN_CHARGE_DATE           : business_types_schema.ASNCHARGEDATE | None = None
    ASN_EXTRA_ACTIVITY_DATE   : business_types_schema.ASNEXTRAACTIVITYDATE | None = None
    ASN_ALLOW_PICK            : business_types_schema.ASNALLOWPICK | None = None
    ASN_VERSION               : business_types_schema.ASNVERSION | None = None
    ASN_VERSION_DATE          : business_types_schema.ASNVERSIONDATE | None = None
    ASN_LOAD_UM               : business_types_schema.ASNLOADUM | None = None
    ASN_UM_UNITS              : business_types_schema.ASNUMUNITS | None = None
    ASN_WMS_STAT              : business_types_schema.ASNWMSSTAT | None = None
    ASN_BLOCK                 : business_types_schema.ASNBLOCK | None = None
    ASN_HU_TYPE               : business_types_schema.ASNHUTYPE | None = None
    ASN_KIT_ORDER             : business_types_schema.ASNKITORDER | None = None
    ASN_SUB_KIT               : business_types_schema.ASNSUBKIT | None = None


class WmsinterfaceZwmsInboundDeliveryCreate(BaseModel):
    """
    Payload schema for sheet '5,6,7,8,24.1' – קבלה למלאי (אספקה נכנסת) רכש מקומי (Outbound)
    """

    # --- Required ---
    Header_1  : Annotated[Header, Field(alias='Header')]
    """
    Message envelope. All 6 fields are infrastructure invariants validated by the firewall.
    """

    # --- Optional ---
    DOC_HEADER: Body | None = None
